/**
 * Emit `tests/fixtures/transfer_sigma.fixture.json` for `tests/transfer_sigma_fixture.rs`.
 *
 * Expects the TS SDK at `../../../ts-sdk/confidential-assets` (sibling of this repo).
 * Build the SDK first so `dist/` exists: `pnpm install && pnpm build` in that package.
 */

import {
  ChunkedAmount,
  ConfidentialTransfer,
  EncryptedAmount,
  TwistedEd25519PrivateKey,
} from "@moveindustries/confidential-assets";
import { readFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

function toHex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("hex");
}

/** Deterministic 32-byte seeds for reproducible fixtures (not production secrets). */
const SENDER_SK_HEX =
  "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20";
const RECIPIENT_SK_HEX =
  "202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f";

async function main(): Promise<void> {
  const senderDecryptionKey = new TwistedEd25519PrivateKey(SENDER_SK_HEX);
  const recipientDecryptionKey = new TwistedEd25519PrivateKey(RECIPIENT_SK_HEX);
  const recipientEncryptionKey = recipientDecryptionKey.publicKey();

  const ALICE_BALANCE = 18446744073709551716n;
  const TRANSFER_AMOUNT = 10n;
  const TEST_CHAIN_ID = 1;
  const TEST_SENDER_ADDR = new Uint8Array(32);
  const TEST_TOKEN_ADDR = new Uint8Array(32);
  const TEST_CONTRACT_ADDR = (() => {
    const a = new Uint8Array(32);
    a[31] = 0x07;
    return a;
  })();

  const aliceConfidentialAmount = ChunkedAmount.fromAmount(ALICE_BALANCE);
  const aliceEncryptedBalance = new EncryptedAmount({
    chunkedAmount: aliceConfidentialAmount,
    publicKey: senderDecryptionKey.publicKey(),
  });
  const senderAvailableBalanceCipherText = aliceEncryptedBalance.getCipherText();

  const transfer = await ConfidentialTransfer.create({
    senderDecryptionKey,
    senderAvailableBalanceCipherText,
    amount: TRANSFER_AMOUNT,
    recipientEncryptionKey,
    chainId: TEST_CHAIN_ID,
    senderAddress: TEST_SENDER_ADDR,
    contractAddress: TEST_CONTRACT_ADDR,
    tokenAddress: TEST_TOKEN_ADDR,
  });

  const sigmaProof = await transfer.genSigmaProof();
  const proofBytes = ConfidentialTransfer.serializeSigmaProof(sigmaProof);

  const tsOk = ConfidentialTransfer.verifySigmaProof({
    senderPrivateKey: senderDecryptionKey,
    recipientPublicKey: recipientEncryptionKey,
    encryptedActualBalance: senderAvailableBalanceCipherText,
    encryptedActualBalanceAfterTransfer: transfer.senderEncryptedAvailableBalanceAfterTransfer,
    encryptedTransferAmountByRecipient: transfer.transferAmountEncryptedByRecipient,
    encryptedTransferAmountBySender: transfer.transferAmountEncryptedBySender,
    sigmaProof,
    chainId: TEST_CHAIN_ID,
    senderAddress: TEST_SENDER_ADDR,
    contractAddress: TEST_CONTRACT_ADDR,
    tokenAddress: TEST_TOKEN_ADDR,
  });
  if (!tsOk) {
    throw new Error("TS verifySigmaProof rejected in-memory proof (SDK bug or bad inputs)");
  }

  let sdkVersion = "unknown";
  try {
    const pkgPath = join(
      __dirname,
      "node_modules/@moveindustries/confidential-assets/package.json",
    );
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { version?: string };
    sdkVersion = pkg.version ?? sdkVersion;
  } catch {
    // ignore
  }

  const doc = {
    skip: false,
    notes:
      "Generated by fixtures/ts/generate.ts — see fixtures/ts/README.md to regenerate.",
    sdk: { name: "@moveindustries/confidential-assets", version: sdkVersion },
    inputs: {
      chain_id: TEST_CHAIN_ID,
      sender_address_hex: toHex(TEST_SENDER_ADDR),
      contract_address_hex: toHex(TEST_CONTRACT_ADDR),
      token_address_hex: toHex(TEST_TOKEN_ADDR),
      sender_auditor_hint_hex: "",
      balance: ALICE_BALANCE.toString(),
      transfer_amount: TRANSFER_AMOUNT.toString(),
      sender_private_key_hex: SENDER_SK_HEX,
      recipient_public_key_hex: toHex(recipientEncryptionKey.toUint8Array()),
    },
    verify: {
      serialized_sigma_proof_hex: toHex(proofBytes),
      encrypted_actual_balance_hex: toHex(aliceEncryptedBalance.getCipherTextBytes()),
      encrypted_balance_after_transfer_hex: toHex(
        transfer.senderEncryptedAvailableBalanceAfterTransfer.getCipherTextBytes(),
      ),
      encrypted_transfer_by_recipient_hex: toHex(
        transfer.transferAmountEncryptedByRecipient.getCipherTextBytes(),
      ),
      encrypted_transfer_by_sender_hex: toHex(
        transfer.transferAmountEncryptedBySender.getCipherTextBytes(),
      ),
      auditor_rows: [] as unknown[],
    },
  };

  process.stdout.write(JSON.stringify(doc, null, 2) + "\n");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
